// This empty schema is used when there's no schema defined in the database.
// This ensures the server doesn't crash upon initial startup

// according to http://facebook.github.io/graphql/June2018/#sec-Root-Operation-Types,
// a schema has to have 'query' field defined and it must be of object type!
// let's add 'mutation' and 'subscription' as well, as they're generated by default using resolverMapper
// and, an object must have a field: http://facebook.github.io/graphql/June2018/#sec-Objects
module.exports = `
schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
type Query {
  _: Boolean
}
type Mutation {
  _: Boolean
}
type Subscription {
  _: Boolean
}
`
