version: '3'

services:
  keycloak:
    image: jboss/keycloak:3.4.3.Final
    ports:
      - "8080:8080"
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin

  postgres:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: aerogear_data_sync_db

  postgres_memeo:
    image: postgres:9.6
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgresql
      POSTGRES_DB: memeolist_db
    volumes:
      - ./examples:/tmp/examples

