CREATE TABLE Profile (
  id SERIAL NOT NULL PRIMARY KEY,
  email CHARACTER VARYING(100) NOT NULL,
  displayname CHARACTER VARYING(100) NOT NULL,
  pictureurl CHARACTER VARYING(500) NOT NULL
);

CREATE TABLE Meme (
  id SERIAL NOT NULL PRIMARY KEY,
  photourl CHARACTER VARYING(500) NOT NULL,
  owner CHARACTER VARYING(100) NOT NULL,
  likes NUMERIC NOT NULL,
  ownerid SERIAL NOT NULL references Profile(id)
);

CREATE TABLE Comment (
  id SERIAL NOT NULL PRIMARY KEY,
  owner CHARACTER VARYING(100) NOT NULL,
  comment CHARACTER VARYING(500) NOT NULL,
  memeid SERIAL NOT NULL references Meme(id)
);
