DROP TABLE IF EXISTS comment;
DROP TABLE IF EXISTS meme;
DROP TABLE IF EXISTS profile;

CREATE TABLE profile (
  id SERIAL NOT NULL PRIMARY KEY,
  email CHARACTER VARYING(100) NOT NULL,
  displayname CHARACTER VARYING(100) NOT NULL,
  pictureurl CHARACTER VARYING(500) NOT NULL
);

CREATE TABLE meme (
  id SERIAL NOT NULL PRIMARY KEY,
  photourl CHARACTER VARYING(500) NOT NULL,
  likes NUMERIC NOT NULL,
  owner SERIAL NOT NULL references profile(id)
);

CREATE TABLE comment (
  id SERIAL NOT NULL PRIMARY KEY,
  comment CHARACTER VARYING(500) NOT NULL,
  owner SERIAL NOT NULL references profile(id),
  memeid SERIAL NOT NULL references meme(id)
);
